CREATE OR REPLACE EXTERNAL TABLE `data_lake.permits` (
`objectid` STRING,
`permitnumber` STRING,
`addressobjectid` STRING,
`parcel_id_num` STRING,
`permittype` STRING,
`permitdescription` STRING,
`commercialorresidential` STRING,
`typeofwork` STRING,
`approvedscopeofwork` STRING,
`permitissuedate` STRING,
`status` STRING,
`applicanttype` STRING,
`contractorname` STRING,
`contractoraddress1` STRING,
`contractoraddress2` STRING,
`contractorcity` STRING,
`contractorstate` STRING,
`contractorzip` STRING,
`mostrecentinsp` STRING,
`opa_account_num` STRING,
`address` STRING,
`unit_type` STRING,
`unit_num` STRING,
`zip` STRING,
`censustract` STRING,
`council_district` STRING,
`opa_owner` STRING,
`systemofrecord` STRING,
`geocode_x` STRING,
`geocode_y` STRING,
`posse_jobid` STRING,
`lat` STRING,
`lng` STRING
)
OPTIONS (
    description = 'Philadelphia Permits - CSV',
    uris = ['gs://rbarad_datalake/phl_permits/*.csv'],
    allow_quoted_newlines = true,
    skip_leading_rows = 1,
    format = 'CSV',
    max_bad_records = 0
)